version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: db_foodgram
    image: postgres:13.10
    env_file: 
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/pg_data

  backend:
    image: chobabcccp/foodgram_backend
    container_name: backend_foodgram
    build:
      context: ../foodgram
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media

  frontend:
    image: chobabcccp/foodgram_frontend
    container_name: frontend_foodgram
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx_foodgram
    image: nginx:1.19.3
    ports:
      - 9001:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend